### PR TITLE
Remove github action workflow

### PR DESCRIPTION
**Pull request by nirarg**
This is moved to be triggered by kubevirt prow

### CODE REVIEW

**Comment by nirarg** [comment]
/hold
The `pull-cloud-provider-kubevirt-unit-tests` job failes:
https://prow.ci.kubevirt.io/?job=pull-cloud-provider-kubevirt-unit-tests

**Comment by dhiller** [comment]
> /hold The `pull-cloud-provider-kubevirt-unit-tests` job failes: https://prow.ci.kubevirt.io/?job=pull-cloud-provider-kubevirt-unit-tests

The `bootstrap` image doesn't have `golang`. See my comment here: https://github.com/kubevirt/project-infra/pull/1988#issuecomment-1081928777

**Comment by nirarg** [comment]
> The `bootstrap` image doesn't have `golang`. See my comment here: [kubevirt/project-infra#1988 (comment)](https://github.com/kubevirt/project-infra/pull/1988#issuecomment-1081928777)

Thanks @dhiller I will change it

**Comment by dhiller** [comment]
Run succeeded: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_cloud-provider-kubevirt/47/pull-cloud-provider-kubevirt-unit-tests/1509151223528296448

**Comment by nirarg** [comment]
Thanks @dhiller 
/hold cancel

**Review by gonzolino — APPROVED** [review]
Does it make sense to also remove the dependant integration?

When I added it, I hoped it would help to keep the dependencies up to date. However, due to interdependencies between the k8s components & libraries the dependant PRs are typically not mergeable.

**Comment by dhiller** [comment]
> Thanks @dhiller /hold cancel

I think you can move the job definition to be reporting by removing `skip_report: false` then, also you might want to remove `optional: false` if you what that job to gate the merge if it fails.

**Comment by dhiller** [comment]
FYI @nirarg

**Comment by nirarg** [comment]
> I think you can move the job definition to be reporting by removing `skip_report: false` then, also you might want to remove `optional: false` if you want that job to gate the merge if it fails.

@dhiller, I Changed it to mandatory, please see https://github.com/kubevirt/project-infra/pull/2004

**Pull request merged**
