### PR TITLE
Start using vendor directory

### PR DESCRIPTION
**Pull request by nirarg**

### CODE REVIEW

**Comment by nirarg** [comment]
@mfranczy do you have any objection of start using vendor directory in the project?
@rhrazdil can you also please take a look?

**Comment by mfranczy** [comment]
> @mfranczy do you have any objection of start using vendor directory in the project?
I think if we use it directly in the project then people with different OSes than Linux would have a problem.

**Comment by mfranczy** [comment]
@nirarg what about using go module proxy?

**Comment by nirarg** [comment]
> @nirarg did you consider to use go module proxy instead of vendoring (to avoid pushing all deps into the github project)?

We have issue in Downstream in which the build system can't download modules from external URL
Using the vendor directory should fix this issue, I thought it can be relevant also upstream
I'm not familiar with `go module proxy`, but from quick review I assume it doesn't fix the issue I have

**Review by mfranczy — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
