### PR TITLE
Update dependencies and fix cloud provider registration

### PR DESCRIPTION
**Pull request by mfranczy**
The change allows to run the cloud provider against the latest KubeVirt 0.51.0

### CODE REVIEW

**Comment by nirarg** [comment]
@mfranczy you upgraded the Go version to 1.18, but the `kubevirt/infra-project` container using Go 1.15 (https://github.com/kubevirt/project-infra/pull/1998#issuecomment-1082994940)
@dhiller can we update the container?

**Comment by dhiller** [comment]
> 



> @mfranczy you upgraded the Go version to 1.18, but the `kubevirt/infra-project` container using Go 1.15 ([kubevirt/project-infra#1998 (comment)](https://github.com/kubevirt/project-infra/pull/1998#issuecomment-1082994940))
> @dhiller can we update the container?

No need to do that, golang image supports the GIMME_GO_VERSION env var with which you can choose the required golang version:

```
docker run -e GIMME_GO_VERSION=1.18 quay.io/kubevirtci/golang:v20220405-a56be88 /bin/bash
Unable to find image 'quay.io/kubevirtci/golang:v20220405-a56be88' locally
v20220405-a56be88: Pulling from kubevirtci/golang
...
Digest: sha256:1a94b8100e729400e86540875e42f61b7704503006f7e1e1adae5c76e4948349
Status: Downloaded newer image for quay.io/kubevirtci/golang:v20220405-a56be88
fatal: not a git repository (or any of the parent directories): .git
go version go1.18 linux/amd64
+ /bin/bash
```

**Comment by nirarg** [comment]
> No need to do that, golang image supports the GIMME_GO_VERSION env var with which you can choose the required golang version:

Thanks @dhiller 
I opened PR for this change:
https://github.com/kubevirt/project-infra/pull/2025

**Review by gonzolino — APPROVED** [review]

**Pull request merged**
