### PR TITLE
Update vendor dependencies for endpointslice controller

### PR DESCRIPTION
**Pull request by kvaps**
required for https://github.com/kubevirt/cloud-provider-kubevirt/pull/331

```
go get 'k8s.io/endpointslice/util@v0.28' 'k8s.io/apiserver@v0.28' 'k8s.io/cloud-provider@v0.28'
go mod tidy
go mod vendor
```

Signed-off-by: Andrei Kvapil <kvapss@gmail.com>

### CODE REVIEW

**Comment by kvaps** [comment]
I don't know why test is failing, locally it is built ok:

```
[+] Building 6.2s (15/15) FINISHED                                                                                                                                               docker:amd64
 => [internal] load build definition from Dockerfile                                                                                                                                     0.9s
 => => transferring dockerfile: 605B                                                                                                                                                     0.1s
 => [internal] load metadata for registry.access.redhat.com/ubi9/ubi-micro:latest                                                                                                        0.7s
 => [internal] load metadata for docker.io/library/golang:1.20.6                                                                                                                         1.6s
 => [internal] load .dockerignore                                                                                                                                                        0.3s
 => => transferring context: 2B                                                                                                                                                          0.1s
 => [stage-1 1/2] FROM registry.access.redhat.com/ubi9/ubi-micro:latest@sha256:7f376b75faf8ea546f28f8529c37d24adcde33dca4103f4897ae19a43d58192b                                          0.0s
 => [builder 1/7] FROM docker.io/library/golang:1.20.6@sha256:010a0ffe47398a3646993df44906c065c526eabf309d01fb0cbc9a5696024a60                                                           0.0s
 => [internal] load build context                                                                                                                                                        1.3s
 => => transferring context: 591.91kB                                                                                                                                                    1.0s
 => CACHED [builder 2/7] WORKDIR /go/src/kubevirt.io/cloud-provider-kubevirt                                                                                                             0.0s
 => CACHED [builder 3/7] COPY go.* ./                                                                                                                                                    0.0s
 => CACHED [builder 4/7] COPY pkg/ pkg/                                                                                                                                                  0.0s
 => CACHED [builder 5/7] COPY cmd/ cmd/                                                                                                                                                  0.0s
 => CACHED [builder 6/7] COPY vendor/ vendor/                                                                                                                                            0.0s
 => CACHED [builder 7/7] RUN CGO_ENABLED=0 GOOS=linux go build -mod=vendor -ldflags="-s -w" -o bin/kubevirt-cloud-controller-manager ./cmd/kubevirt-cloud-controller-manager             0.0s
 => CACHED [stage-1 2/2] COPY --from=builder /go/src/kubevirt.io/cloud-provider-kubevirt/bin/kubevirt-cloud-controller-manager /bin/kubevirt-cloud-controller-manager                    0.0s
 => exporting to image                                                                                                                                                                   0.3s
 => => exporting layers                                                                                                                                                                  0.0s
 => => writing image sha256:81be6df64c5480450a78eb7c9dd095ff4073b18d88325aa24ffc3992ee5cc52a                                                                                             0.1s
 => => naming to 127.0.0.1:40349/kubevirt-cloud-controller-manager:main                                                                                                                  0.1s

 1 warning found (use --debug to expand):
 - FromPlatformFlagConstDisallowed: FROM --platform flag should not use constant value "linux/amd64" (line 1)
 ```

**Comment by qinqon** [comment]
/retest

Issue was fixed.

**Pull request merged**
