### PR TITLE
update x/net pkg

### PR DESCRIPTION
**Pull request by davidvossel**

### CODE REVIEW

**Comment by mfranczy** [comment]
Tests fail with:
> error: error validating "STDIN": error validating data: ValidationError(KubevirtMachineTemplate.spec.template.spec): unknown field "virtualMachineBootstrapCheck" in io.x-k8s.cluster.infrastructure.v1alpha1.KubevirtMachineTemplate.spec.template.spec; if you choose to ignore these errors, turn validation off with --validate=false

**Comment by davidvossel** [comment]
i had to update the capk version to fix that error.

**Comment by mfranczy** [comment]
sure

/approve
/lgtm

**Pull request merged**
