### PR TITLE
Load balancer selector changes

### PR DESCRIPTION
**Pull request by nirarg**
Change LoadBalancer use existing labels on VMI instead of setting new

### CODE REVIEW

**Comment by nirarg** [comment]
@mfranczy @qinqon @davidvossel 
I opened the PR to start have review on the logic changes
The PR is still missing unit tests and comments fixes

**Comment by qinqon** [comment]
Let's fix the CI issue first before review, does not make sense to review non working code.

**Comment by mfranczy** [comment]
@nirarg could you as well add a short note to documentation about labels that should be added to VMs?

**Comment by nirarg** [comment]
@qinqon @mfranczy @davidvossel 
The PR is ready for review

**Review by qinqon — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
